# Generated by Django 5.1 on 2026-07-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('director', 'Director'), ('sales_executive', 'Sales Executive'), ('project_manager', 'Project Manager'), ('account_manager', 'Account Manager'), ('seo_specialist', 'SEO Specialist'), ('google_ads_specialist', 'Google Ads Specialist'), ('meta_ads_specialist', 'Meta Ads Specialist'), ('web_developer', 'Web Developer'), ('ui_ux_designer', 'UI/UX Designer'), ('content_writer', 'Content Writer'), ('qa_specialist', 'QA Specialist'), ('academy_admin', 'Academy Admin'), ('mentor', 'Mentor'), ('trainer', 'Trainer'), ('student', 'Student'), ('intern', 'Intern'), ('placement_coordinator', 'Placement Coordinator'), ('client_owner', 'Business Owner'), ('client_member', 'Team Member')], default='client_owner', max_length=30),
        ),
    ]
