# Generated by Django 5.1.6 on 2026-07-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('director', 'Director'), ('sales_executive', 'Sales Executive'), ('office_manager', 'Office Manager'), ('project_manager', 'Project Manager'), ('account_manager', 'Account Manager'), ('seo_specialist', 'SEO Specialist'), ('google_ads_specialist', 'Google Ads Specialist'), ('meta_ads_specialist', 'Meta Ads Specialist'), ('web_developer', 'Web Developer'), ('ui_ux_designer', 'UI/UX Designer'), ('content_writer', 'Content Writer'), ('qa_specialist', 'QA Specialist'), ('freelancer', 'Freelancer'), ('academy_admin', 'Academy Admin'), ('mentor', 'Mentor'), ('trainer', 'Trainer'), ('student', 'Student'), ('intern', 'Intern'), ('placement_coordinator', 'Placement Coordinator'), ('client_owner', 'Business Owner'), ('client_member', 'Team Member'), ('partner', 'DGC (Digital Growth Consultant)')], default='client_owner', max_length=30),
        ),
    ]
