# Generated by Django 5.1 on 2026-08-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_paid_at_invoice_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='sent', max_length=20),
        ),
    ]
