# Generated by Django 6.0.7 on 2026-07-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_lead_assigned_to_lead_converted_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=120)),
                ('application_type', models.CharField(choices=[('fulltime', 'Full-time'), ('internship', 'Internship'), ('contract', 'Contract')], default='fulltime', max_length=20)),
                ('experience', models.CharField(blank=True, max_length=120)),
                ('portfolio_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('cover_letter', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'Under Review'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
