# Generated by Django 6.0.7 on 2026-07-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='portfolio_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
