# Generated by Django 5.1 on 2026-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_os_hub_abc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('review', 'Under Review'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=20),
        ),
    ]
