# Generated by Django 5.1 on 2026-08-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_jobapplication_status_alter_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('department', models.CharField(max_length=80)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full-time', max_length=20)),
                ('location', models.CharField(default='Surat / Hybrid', max_length=120)),
                ('summary', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['department', 'title'],
            },
        ),
    ]
