# Generated by Django 5.1 on 2026-08-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_jobopening_company_name_jobopening_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=120)),
                ('client', models.CharField(max_length=160)),
                ('result', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('image', models.URLField(blank=True, max_length=500)),
                ('impact_areas', models.JSONField(blank=True, default=list)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('narrative', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Case studies',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('pricing', 'Pricing page'), ('general', 'General (home / pricing)'), ('startup', 'Startup Plan page'), ('lp_ai_dm', 'Digital Launchpad landing page')], db_index=True, max_length=20)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['group', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.CharField(max_length=40)),
                ('price_monthly', models.CharField(blank=True, max_length=40)),
                ('price_annual', models.CharField(blank=True, max_length=40)),
                ('period', models.CharField(blank=True, max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('highlight', models.BooleanField(default=False)),
                ('blurb', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=80)),
                ('result', models.CharField(max_length=160)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('icon', models.CharField(blank=True, max_length=20)),
                ('short', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('is_flagship', models.BooleanField(db_index=True, default=False)),
                ('flagship_features', models.JSONField(blank=True, default=list)),
                ('popular', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.URLField(blank=True, max_length=500)),
                ('contact_bg_image', models.URLField(blank=True, max_length=500)),
                ('about_team_image', models.URLField(blank=True, max_length=500)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_address', models.CharField(blank=True, max_length=300)),
                ('contact_hours', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StartupPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=4)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('short', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('duration', models.CharField(blank=True, max_length=60)),
                ('icon', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('label', models.CharField(max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=160)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('initials', models.CharField(blank=True, max_length=6)),
                ('bio', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('is_founder', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_founder', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('initials', models.CharField(blank=True, max_length=6)),
                ('photo', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TitleDescBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('why_choose_us', 'Why Choose Us (home / services / about)'), ('startup_promises', 'Startup Plan — Promises'), ('startup_for', "Startup Plan — Who it's for"), ('f2c_pipeline', 'Factory-to-Customer Pipeline (home / services)'), ('model_steps', 'Dual Model steps (home / about)'), ('industries', 'Industries served'), ('team_departments', 'Team — Departments'), ('team_roles', 'Team — Capacity by role'), ('careers_perks', 'Careers — Perks'), ('academy_process', 'Careers — Academy process steps'), ('audience_tags', 'Home — Audience tags'), ('hero_points', 'Home — Hero bullet points')], db_index=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('desc', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji, e.g. 🏭', max_length=20)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('badge', models.CharField(blank=True, help_text='Short label, e.g. a headcount like "25"', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['section', 'order', 'id'],
            },
        ),
    ]
