# Generated by Django 5.1 on 2026-08-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_seed_cms_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='image_upload',
            field=models.FileField(blank=True, help_text='Uploading a photo here overrides the Image URL above.', upload_to='team/'),
        ),
    ]
