# Generated by Django 5.1.6 on 2026-07-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgcapplication',
            name='temp_password',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
