# Generated by Django 5.1.6 on 2026-07-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_dgc_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='reselleroffer',
            name='billing_note',
            field=models.CharField(blank=True, help_text='e.g. per year, one-time', max_length=80),
        ),
        migrations.AddField(
            model_name='reselleroffer',
            name='market_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested market sell price (high)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='reselleroffer',
            name='market_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Suggested market sell price (low)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dgcapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('review', 'Under Review'), ('approved', 'Approved'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
