# Generated by Django 5.1.6 on 2026-07-13 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_reseller_market_pricing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_partner_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnerorder',
            name='due_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerorder',
            name='work_notes',
            field=models.TextField(blank=True),
        ),
    ]
