# Generated by Django 5.1.6 on 2026-07-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_os_hub_abc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgcapplication',
            name='aadhaar_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits of Aadhaar', max_length=4),
        ),
        migrations.AddField(
            model_name='dgcapplication',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='dgcapplication',
            name='bank_account',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='dgcapplication',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dgcapplication',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN for KYC', max_length=20),
        ),
        migrations.AddField(
            model_name='dgcapplication',
            name='upi_id',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
