# Generated by Django 5.1 on 2026-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_dgcapplication_status_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('paid', 'Paid')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnerlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnerorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
