"""Declarative registry driving the generic /ops/cms/ CRUD (CMSListView /
CMSEditView / CMSToggleView / CMSDeleteView in operations/cms_views.py).
One entry per public-site content model — add a new content type here
instead of hand-writing another List/Edit/Toggle/Delete view+template set."""

from website.models import (
    CaseStudy,
    FAQ,
    PricingTier,
    ProjectBlock,
    Service,
    SiteSettings,
    StartupPhase,
    StatBlock,
    TeamMember,
    Testimonial,
    TitleDescBlock,
)

from .cms_forms import (
    CaseStudyForm,
    FAQForm,
    PricingTierForm,
    ProjectBlockForm,
    ServiceForm,
    SiteSettingsForm,
    StartupPhaseForm,
    StatBlockForm,
    TeamMemberForm,
    TestimonialForm,
    TitleDescBlockForm,
)

CMS_REGISTRY = {
    'blocks': {
        'label': 'Content Blocks',
        'help': 'Reusable title/desc cards — Why Choose Us, Startup Plan, industries, team departments, etc. Filter by section.',
        'model': TitleDescBlock,
        'form': TitleDescBlockForm,
        'order_fields': ['section', 'order', 'id'],
        'columns': [('section', 'get_section_display'), ('title', 'title'), ('is_active', 'is_active')],
        'singleton': False,
    },
    'stats': {
        'label': 'Stats',
        'help': 'The "12+ Years Experience" style stat strip shown on home/about/team/startup/careers.',
        'model': StatBlock,
        'form': StatBlockForm,
        'order_fields': ['order', 'id'],
        'columns': [('label', 'label'), ('value', 'value'), ('is_active', 'is_active')],
        'singleton': False,
    },
    'projects': {
        'label': 'Recent Projects',
        'help': 'Project cards on home / services / our-work / careers / join.',
        'model': ProjectBlock,
        'form': ProjectBlockForm,
        'order_fields': ['order', 'id'],
        'columns': [('title', 'title'), ('category', 'category'), ('is_active', 'is_active')],
        'singleton': False,
    },
    'testimonials': {
        'label': 'Testimonials',
        'help': 'Client quotes on the home page.',
        'model': Testimonial,
        'form': TestimonialForm,
        'order_fields': ['order', 'id'],
        'columns': [('name', 'name'), ('role', 'role'), ('is_active', 'is_active')],
        'singleton': False,
    },
    'faqs': {
        'label': 'FAQs',
        'help': 'Pricing / general / Startup Plan / Digital Launchpad FAQs. Filter by group.',
        'model': FAQ,
        'form': FAQForm,
        'order_fields': ['group', 'order', 'id'],
        'columns': [('group', 'get_group_display'), ('question', 'question'), ('is_active', 'is_active')],
        'singleton': False,
    },
    'team': {
        'label': 'Team',
        'help': 'Founders + core team, shown on /team/ and the home/about preview.',
        'model': TeamMember,
        'form': TeamMemberForm,
        'order_fields': ['-is_founder', 'order', 'id'],
        'columns': [('name', 'name'), ('role', 'role'), ('is_founder', 'is_founder'), ('is_active', 'is_active')],
        'singleton': False,
    },
    'services': {
        'label': 'Services',
        'help': '/services/ catalog. Mark up to 3 as Flagship to show them on the home page.',
        'model': Service,
        'form': ServiceForm,
        'order_fields': ['order', 'id'],
        'columns': [('title', 'title'), ('is_flagship', 'is_flagship'), ('is_active', 'is_active')],
        'singleton': False,
    },
    'case-studies': {
        'label': 'Case Studies',
        'help': '/case-studies/ and individual case study pages.',
        'model': CaseStudy,
        'form': CaseStudyForm,
        'order_fields': ['order', 'id'],
        'columns': [('title', 'title'), ('client', 'client'), ('is_active', 'is_active')],
        'singleton': False,
    },
    'pricing': {
        'label': 'Pricing Tiers',
        'help': '/pricing/ plans.',
        'model': PricingTier,
        'form': PricingTierForm,
        'order_fields': ['order', 'id'],
        'columns': [('name', 'name'), ('price', 'price'), ('is_active', 'is_active')],
        'singleton': False,
    },
    'startup-phases': {
        'label': 'Startup Plan Phases',
        'help': '/startup/ 5-phase plan.',
        'model': StartupPhase,
        'form': StartupPhaseForm,
        'order_fields': ['order', 'id'],
        'columns': [('num', 'num'), ('title', 'title'), ('is_active', 'is_active')],
        'singleton': False,
    },
    'site-settings': {
        'label': 'Site Settings',
        'help': 'Site-wide images and contact details — one row, no add/delete.',
        'model': SiteSettings,
        'form': SiteSettingsForm,
        'order_fields': ['id'],
        'columns': [],
        'singleton': True,
    },
}
