# Generated by Django 5.1 on 2026-08-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
