# Generated by Django 5.1 on 2026-08-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_admissionapplication_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('goal', models.TextField()),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('All levels', 'All levels')], default='Beginner', max_length=20)),
                ('duration', models.CharField(default='4 weeks', max_length=40)),
                ('format', models.CharField(default='Self-paced', max_length=40)),
                ('modules_count', models.PositiveIntegerField(default=0)),
                ('topics_count', models.PositiveIntegerField(default=0)),
                ('price', models.CharField(help_text='Display string, e.g. ₹16,999', max_length=20)),
                ('salary_range', models.CharField(blank=True, max_length=40)),
                ('featured', models.BooleanField(default=False)),
                ('enrolled', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('gains', models.JSONField(blank=True, default=list)),
                ('includes', models.JSONField(blank=True, default=list)),
                ('learn_modules', models.JSONField(blank=True, default=list)),
                ('ideal_paths', models.JSONField(blank=True, default=list)),
                ('overview', models.JSONField(blank=True, default=list)),
                ('curriculum', models.JSONField(blank=True, default=list)),
                ('reviews', models.JSONField(blank=True, default=list)),
                ('career_label', models.CharField(blank=True, max_length=80)),
                ('career_min', models.CharField(blank=True, max_length=20)),
                ('career_max', models.CharField(blank=True, max_length=20)),
                ('highlight_quote', models.TextField(blank=True)),
                ('highlight_author', models.CharField(blank=True, max_length=120)),
                ('starts_with', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
